version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: vitrine-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - vitrine-network

  nginx:
    image: nginx:alpine
    container_name: vitrine-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - vitrine-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: vitrine-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vitrine_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: vitrine_user
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - vitrine-network

networks:
  vitrine-network:
    driver: bridge

volumes:
  dbdata:
    driver: local 